  tests = [
        "MISFIRE_MONITORING",
        "FUEL_SYSTEM_MONITORING",
        "COMPONENT_MONITORING",
        "CATALYST_MONITORING",
        "HEATED_CATALYST_MONITORING",
        "EVAPORATIVE_SYSTEM_MONITORING",
        "SECONDARY_AIR_SYSTEM_MONITORING",
        "OXYGEN_SENSOR_MONITORING",
        "OXYGEN_SENSOR_HEATER_MONITORING",
        "EGR_VVT_SYSTEM_MONITORING",
        "NMHC_CATALYST_MONITORING",
        "NOX_SCR_AFTERTREATMENT_MONITORING",
        "BOOST_PRESSURE_MONITORING",
        "EXHAUST_GAS_SENSOR_MONITORING",
        "PM_FILTER_MONITORING",
    ]